name: Build macOS App

on:
  push:
    branches:
      - main  # Change if your branch name is different (like master)

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'

    - name: Enable macOS support
      run: flutter config --enable-macos-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Build macOS app
      run: flutter build macos

    - name: Upload macOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/macos/Build/Products/Release/
